spring.datasource.url=jdbc:postgresql://ep-wandering-block-axz25h9x.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_OWFl9zxBS6Nk
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=miClaveSecretaSuperSeguraParaElProyectoIntegrador2026
jwt.expiration=86400000